#!/usr/bin/env bash
# kills the infinity and beyond program using sigkill signal

# Get the pid of the running process
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinite process
if [ -n "$id" ]
then
  kill -9 "$id"
fi
